- hosts: all
  become: yes
  tasks:
  - name: "Install NPM repo"
    shell: curl -sL https://rpm.nodesource.com/setup_14.x | bash -
  - name: "Install NPM depenencies"
    yum:
      name:
        - nodejs
      state: latest
        