- name: Install node and npm
  hosts: all
  tasks:
    - name: Update apt repo and cache
      apt: curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
        