- name: Install NodeJs
  hosts: all
  tasks:
    - name: Install Node
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt install nodejs
      args:
        executable: /bin/bash
         - name: Install nodejs package
      become: true
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
        